# Generated by Django 5.1.7 on 2025-06-27 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SearchApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name="Register",
        ),
    ]
