# Generated by Django 5.1.7 on 2025-07-08 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SearchApp", "0005_founditem_is_claimed"),
    ]

    operations = [
        migrations.AddField(
            model_name="lostitem",
            name="is_matched",
            field=models.BooleanField(default=False),
        ),
    ]
